nelmio_api_doc:
    documentation:
        host: localhost:8000
        schemes: [http]
        info:
            title: Project Flayer
            description: "Swagger documentation to demonstrate the API that make a simple CRUD RestFull service that support file uploads."
            version: 1.0.0
            contact: { email: taziabdelmounaim@gmail.com, name: Abdel Mounaim Tazi}
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value: Bearer {jwt}'
                name: Authorization
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc?.*$) # Accepts routes under /api except /api/doc
